import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next";
import TanStackProvider from "@/lib/TanStackProvider";

const pretendard = localFont({
  src: "../assets/fonts/PretendardVariable.woff2",
  variable: "--font-pretendard",
  display: "swap",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko-KR">
      <body className={`${pretendard.variable} font-pretendard antialiased`}>
        <TanStackProvider>
          {children}
          <SpeedInsights />
        </TanStackProvider>
      </body>
    </html>
  );
}
