import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next";
import TanStackProvider from "@/lib/TanStackProvider";

const geistSans = localFont({
  src: "../assets/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../assets/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko-KR">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <TanStackProvider>
          {children}
          <SpeedInsights />
        </TanStackProvider>
      </body>
    </html>
  );
}
