name: Upload coverage reports to Codecov

on:
  pull_request:
    branches: [main, dev]

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run build
        run: npm run build

      - name: Run test
        run: npm run test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
